/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "v1.h"

/*
	Procura o maior valor do vetor informado no lado do cliente e retorna em &result
*/
float *
getmaior_50_svc(vetor *argp, struct svc_req *rqstp)
{
	static float result = -99999;

	for (int i = 0; i < 10; i++)
	{
		if (argp->vetor[i] > result)
		{
			result = argp->vetor[i];
		}
	}
	return &result;
}

/*
	Procura o menor valor do vetor informado no lado do cliente e retorna em &result
*/
float *
getmenor_50_svc(vetor *argp, struct svc_req *rqstp)
{
	static float result = 99999;
	for (int i = 0; i < 10; i++)
	{
		if (argp->vetor[i] < result)
		{
			result = argp->vetor[i];
		}
	}
	return &result;
}
